### ISSUE TITLE
More editors settings to customise

### ISSUE THREAD

**Issue by narqo** [emmetio/emmet-eclipse#3]
It would be nice if one could provide more settings to customize output, e.g. code style. For example do not indent `CSS`-values with space after semicolon:

``` css
.some-class
{
    boder:1px solid;
}
```
